### ISSUE TITLE
package is not on npm

### ISSUE THREAD

**Issue by masi** [csstools/postcss-is-pseudo-class#2]
But the installation docs say so.

I have read that the package has stil issues, but I'd be content with the limitation that each rule may only have one `:is()` selector.

Cheers,
Masi

**Comment by Antonio-Laguna** [comment]
@masi I'm really sorry this was long forgotten. I was doing maintenance and just noticed this. I'm going to archive this repo to avoid any further confusion. We got to release a different version of this package which you can see here: https://www.npmjs.com/package/@csstools/postcss-is-pseudo-class

And also bundled with preset-env. 

If you find any issue, we'd love if you report it here: https://github.com/csstools/postcss-plugins

Thanks for your patience
